{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.spotbugs",
    "module": "spotbugs-annotations",
    "version": "4.8.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "files": [
        {
          "name": "spotbugs-annotations-4.8.6.jar",
          "url": "spotbugs-annotations-4.8.6.jar",
          "size": 15297,
          "sha512": "ebe5bca26efc72b82c168b65f8f4b1b55768e0464edb9e732e48bcb05b3de7e761e50f0da46e96f02258b4bc4443f4e4a5e7d53956b17161674238b564f6018d",
          "sha256": "4548b74a815ed44f5480ca4f06204a8b00809dc7e5f6a825a9edf18f40377b65",
          "sha1": "1dcffed3e561ed32134a0dff4717f19bc2fdf4d8",
          "md5": "0806b237c67c69869506ce3ced9a722f"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "org.apache.logging.log4j",
          "module": "log4j-core",
          "version": {
            "strictly": "[2.17.1, 3[",
            "requires": "[2.17.1, 3["
          },
          "reason": "CVE-2021-44228, CVE-2021-45046, CVE-2021-45105, CVE-2021-44832: Log4j vulnerable to remote code execution and other critical security vulnerabilities"
        },
        {
          "group": "ch.qos.logback",
          "module": "logback-core",
          "version": {
            "strictly": "[1.2.9, 2[",
            "requires": "[1.2.9, 2["
          },
          "reason": "CVE-2021-42550: Logback vulnerable to remote code execution vulnerabilities"
        }
      ],
      "files": [
        {
          "name": "spotbugs-annotations-4.8.6.jar",
          "url": "spotbugs-annotations-4.8.6.jar",
          "size": 15297,
          "sha512": "ebe5bca26efc72b82c168b65f8f4b1b55768e0464edb9e732e48bcb05b3de7e761e50f0da46e96f02258b4bc4443f4e4a5e7d53956b17161674238b564f6018d",
          "sha256": "4548b74a815ed44f5480ca4f06204a8b00809dc7e5f6a825a9edf18f40377b65",
          "sha1": "1dcffed3e561ed32134a0dff4717f19bc2fdf4d8",
          "md5": "0806b237c67c69869506ce3ced9a722f"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-annotations-4.8.6-javadoc.jar",
          "url": "spotbugs-annotations-4.8.6-javadoc.jar",
          "size": 224175,
          "sha512": "8428d01d6061f5f8f50177fe3c6649c20a4557dcb487b5f728e57565718d5758082b3fb8978ce7f0e85e11444db0dc6097cb099f2580311c6a9b76cbcbef9a5e",
          "sha256": "0f095f2d0c766b3e2c21ebc226b4f228898fa8c141736f7615a47a2e3be14ba7",
          "sha1": "3fec3fb7829792b715d60efa999481b14cdc94da",
          "md5": "2d70e2c0b1ed8e0730c24a2217487ebc"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spotbugs-annotations-4.8.6-sources.jar",
          "url": "spotbugs-annotations-4.8.6-sources.jar",
          "size": 24186,
          "sha512": "4a8e3c021261ada3bd6fb9741426ef14afffb49fcb8853ed86a7c42d711e5816ea553ff9ca826fd38c6516d6d3aadef0b8e345e37e15925dd78277353bc7480e",
          "sha256": "b5d0110b70b9c44915f2c3375d1b700acb6d409152baf70030787d17a684469b",
          "sha1": "062e2cc9cfe009786e8f7b5ac6421668cb8a62b1",
          "md5": "7b9d74e907169ff381e0f1a7a7a1b18f"
        }
      ]
    }
  ]
}
