{
  "formatVersion": "1.1",
  "component": {
    "group": "org.springframework.boot",
    "module": "spring-boot-starter-security",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.2.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-4.0.0.jar",
          "url": "spring-boot-starter-security-4.0.0.jar",
          "size": 4740,
          "sha512": "d259701aab86b9f78e6eb5705e19cc485d1ca60d69d04b62e12350d22e53605cde616ee51610d1052ea305684c94775c51171c83229ac451a2c743c74a302383",
          "sha256": "59468cd0446e52d3651bddac6e0dde6883c0677bb1822dd0f9f53bc96fd3b3dc",
          "sha1": "79db96e5a5fb84ace88d7d7a93883e01875e0471",
          "md5": "f31e46a9f419f8de9ee8852c1ff6c433"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-security",
          "version": {
            "requires": "4.0.0"
          }
        },
        {
          "group": "org.springframework",
          "module": "spring-aop",
          "version": {
            "requires": "7.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "spring-boot-starter-security-4.0.0.jar",
          "url": "spring-boot-starter-security-4.0.0.jar",
          "size": 4740,
          "sha512": "d259701aab86b9f78e6eb5705e19cc485d1ca60d69d04b62e12350d22e53605cde616ee51610d1052ea305684c94775c51171c83229ac451a2c743c74a302383",
          "sha256": "59468cd0446e52d3651bddac6e0dde6883c0677bb1822dd0f9f53bc96fd3b3dc",
          "sha1": "79db96e5a5fb84ace88d7d7a93883e01875e0471",
          "md5": "f31e46a9f419f8de9ee8852c1ff6c433"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-4.0.0-javadoc.jar",
          "url": "spring-boot-starter-security-4.0.0-javadoc.jar",
          "size": 4740,
          "sha512": "d259701aab86b9f78e6eb5705e19cc485d1ca60d69d04b62e12350d22e53605cde616ee51610d1052ea305684c94775c51171c83229ac451a2c743c74a302383",
          "sha256": "59468cd0446e52d3651bddac6e0dde6883c0677bb1822dd0f9f53bc96fd3b3dc",
          "sha1": "79db96e5a5fb84ace88d7d7a93883e01875e0471",
          "md5": "f31e46a9f419f8de9ee8852c1ff6c433"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "spring-boot-starter-security-4.0.0-sources.jar",
          "url": "spring-boot-starter-security-4.0.0-sources.jar",
          "size": 4740,
          "sha512": "d259701aab86b9f78e6eb5705e19cc485d1ca60d69d04b62e12350d22e53605cde616ee51610d1052ea305684c94775c51171c83229ac451a2c743c74a302383",
          "sha256": "59468cd0446e52d3651bddac6e0dde6883c0677bb1822dd0f9f53bc96fd3b3dc",
          "sha1": "79db96e5a5fb84ace88d7d7a93883e01875e0471",
          "md5": "f31e46a9f419f8de9ee8852c1ff6c433"
        }
      ]
    }
  ]
}
